// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/pb/project/v1/project.proto

package projectv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IssueCount    int32                  `protobuf:"varint,4,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type UpdateProjectWithIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // Cannot be empty
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`       // New issue being added
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectWithIssueRequest) Reset() {
	*x = UpdateProjectWithIssueRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectWithIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectWithIssueRequest) ProtoMessage() {}

func (x *UpdateProjectWithIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectWithIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectWithIssueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProjectWithIssueRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectWithIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type UpdateProjectWithIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IssueCount    int32                  `protobuf:"varint,2,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"` // Updated issue count
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // Status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectWithIssueResponse) Reset() {
	*x = UpdateProjectWithIssueResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectWithIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectWithIssueResponse) ProtoMessage() {}

func (x *UpdateProjectWithIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectWithIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectWithIssueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProjectWithIssueResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectWithIssueResponse) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

func (x *UpdateProjectWithIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamProjectUpdates (Bidirectional)
type ProjectUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // Cannot be empty
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                        // Cannot be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectUpdateRequest) Reset() {
	*x = ProjectUpdateRequest{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUpdateRequest) ProtoMessage() {}

func (x *ProjectUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectUpdateRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectUpdateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ProjectUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`     // Project ID being updated
	IssueCount    int32                  `protobuf:"varint,2,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"` // Updated issue count
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                          // Additional messages from the server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectUpdateResponse) Reset() {
	*x = ProjectUpdateResponse{}
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUpdateResponse) ProtoMessage() {}

func (x *ProjectUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_project_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_project_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ProjectUpdateResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectUpdateResponse) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

func (x *ProjectUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_pb_project_v1_project_proto protoreflect.FileDescriptor

const file_pkg_pb_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/pb/project/v1/project.proto\x12\n" +
	"project.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dproto/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xc4\x01\n" +
	"\aProject\x12:\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x1b\xfaB\x18r\x16\x10\x01\x18$2\x10^[a-zA-Z0-9_-]+$R\tprojectId\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xe8\aR\vdescription\x12\x1f\n" +
	"\vissue_count\x18\x04 \x01(\x05R\n" +
	"issueCount\"t\n" +
	"\x14CreateProjectRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xe8\aR\vdescription\"F\n" +
	"\x15CreateProjectResponse\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.project.v1.ProjectR\aproject\"O\n" +
	"\x11GetProjectRequest\x12:\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x1b\xfaB\x18r\x16\x10\x01\x18$2\x10^[a-zA-Z0-9_-]+$R\tprojectId\"C\n" +
	"\x12GetProjectResponse\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.project.v1.ProjectR\aproject\"\xb0\x01\n" +
	"\x14UpdateProjectRequest\x12:\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x1b\xfaB\x18r\x16\x10\x01\x18$2\x10^[a-zA-Z0-9_-]+$R\tprojectId\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xe8\aR\vdescription\"F\n" +
	"\x15UpdateProjectResponse\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.project.v1.ProjectR\aproject\"R\n" +
	"\x14DeleteProjectRequest\x12:\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x1b\xfaB\x18r\x16\x10\x01\x18$2\x10^[a-zA-Z0-9_-]+$R\tprojectId\"G\n" +
	"\x14ListProjectsResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.project.v1.ProjectR\bprojects\"b\n" +
	"\x1dUpdateProjectWithIssueRequest\x12&\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tprojectId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"z\n" +
	"\x1eUpdateProjectWithIssueResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vissue_count\x18\x02 \x01(\x05R\n" +
	"issueCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"w\n" +
	"\x14ProjectUpdateRequest\x12&\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tprojectId\x127\n" +
	"\x06action\x18\x02 \x01(\tB\x1f\xfaB\x1cr\x1a\x10\x01\x18\n" +
	"2\x14^(subscribe|update)$R\x06action\"q\n" +
	"\x15ProjectUpdateResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vissue_count\x18\x02 \x01(\x05R\n" +
	"issueCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xb9\x06\n" +
	"\x0eProjectService\x12m\n" +
	"\rCreateProject\x12 .project.v1.CreateProjectRequest\x1a!.project.v1.CreateProjectResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/projects\x12n\n" +
	"\n" +
	"GetProject\x12\x1d.project.v1.GetProjectRequest\x1a\x1e.project.v1.GetProjectResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/projects/{project_id}\x12z\n" +
	"\rUpdateProject\x12 .project.v1.UpdateProjectRequest\x1a!.project.v1.UpdateProjectResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/projects/{project_id}\x12l\n" +
	"\rDeleteProject\x12 .project.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/projects/{project_id}\x12^\n" +
	"\fListProjects\x12\x16.google.protobuf.Empty\x1a .project.v1.ListProjectsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/projects\x12\x9c\x01\n" +
	"\x16UpdateProjectWithIssue\x12).project.v1.UpdateProjectWithIssueRequest\x1a*.project.v1.UpdateProjectWithIssueResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/projects/{project_id}/issues\x12_\n" +
	"\x14StreamProjectUpdates\x12 .project.v1.ProjectUpdateRequest\x1a!.project.v1.ProjectUpdateResponse(\x010\x01B\x1dZ\x1bpkg/pb/project/v1;projectv1b\x06proto3"

var (
	file_pkg_pb_project_v1_project_proto_rawDescOnce sync.Once
	file_pkg_pb_project_v1_project_proto_rawDescData []byte
)

func file_pkg_pb_project_v1_project_proto_rawDescGZIP() []byte {
	file_pkg_pb_project_v1_project_proto_rawDescOnce.Do(func() {
		file_pkg_pb_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_project_v1_project_proto_rawDesc), len(file_pkg_pb_project_v1_project_proto_rawDesc)))
	})
	return file_pkg_pb_project_v1_project_proto_rawDescData
}

var file_pkg_pb_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_pb_project_v1_project_proto_goTypes = []any{
	(*Project)(nil),                        // 0: project.v1.Project
	(*CreateProjectRequest)(nil),           // 1: project.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),          // 2: project.v1.CreateProjectResponse
	(*GetProjectRequest)(nil),              // 3: project.v1.GetProjectRequest
	(*GetProjectResponse)(nil),             // 4: project.v1.GetProjectResponse
	(*UpdateProjectRequest)(nil),           // 5: project.v1.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),          // 6: project.v1.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),           // 7: project.v1.DeleteProjectRequest
	(*ListProjectsResponse)(nil),           // 8: project.v1.ListProjectsResponse
	(*UpdateProjectWithIssueRequest)(nil),  // 9: project.v1.UpdateProjectWithIssueRequest
	(*UpdateProjectWithIssueResponse)(nil), // 10: project.v1.UpdateProjectWithIssueResponse
	(*ProjectUpdateRequest)(nil),           // 11: project.v1.ProjectUpdateRequest
	(*ProjectUpdateResponse)(nil),          // 12: project.v1.ProjectUpdateResponse
	(*emptypb.Empty)(nil),                  // 13: google.protobuf.Empty
}
var file_pkg_pb_project_v1_project_proto_depIdxs = []int32{
	0,  // 0: project.v1.CreateProjectResponse.project:type_name -> project.v1.Project
	0,  // 1: project.v1.GetProjectResponse.project:type_name -> project.v1.Project
	0,  // 2: project.v1.UpdateProjectResponse.project:type_name -> project.v1.Project
	0,  // 3: project.v1.ListProjectsResponse.projects:type_name -> project.v1.Project
	1,  // 4: project.v1.ProjectService.CreateProject:input_type -> project.v1.CreateProjectRequest
	3,  // 5: project.v1.ProjectService.GetProject:input_type -> project.v1.GetProjectRequest
	5,  // 6: project.v1.ProjectService.UpdateProject:input_type -> project.v1.UpdateProjectRequest
	7,  // 7: project.v1.ProjectService.DeleteProject:input_type -> project.v1.DeleteProjectRequest
	13, // 8: project.v1.ProjectService.ListProjects:input_type -> google.protobuf.Empty
	9,  // 9: project.v1.ProjectService.UpdateProjectWithIssue:input_type -> project.v1.UpdateProjectWithIssueRequest
	11, // 10: project.v1.ProjectService.StreamProjectUpdates:input_type -> project.v1.ProjectUpdateRequest
	2,  // 11: project.v1.ProjectService.CreateProject:output_type -> project.v1.CreateProjectResponse
	4,  // 12: project.v1.ProjectService.GetProject:output_type -> project.v1.GetProjectResponse
	6,  // 13: project.v1.ProjectService.UpdateProject:output_type -> project.v1.UpdateProjectResponse
	13, // 14: project.v1.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	8,  // 15: project.v1.ProjectService.ListProjects:output_type -> project.v1.ListProjectsResponse
	10, // 16: project.v1.ProjectService.UpdateProjectWithIssue:output_type -> project.v1.UpdateProjectWithIssueResponse
	12, // 17: project.v1.ProjectService.StreamProjectUpdates:output_type -> project.v1.ProjectUpdateResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_pb_project_v1_project_proto_init() }
func file_pkg_pb_project_v1_project_proto_init() {
	if File_pkg_pb_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_project_v1_project_proto_rawDesc), len(file_pkg_pb_project_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_project_v1_project_proto_goTypes,
		DependencyIndexes: file_pkg_pb_project_v1_project_proto_depIdxs,
		MessageInfos:      file_pkg_pb_project_v1_project_proto_msgTypes,
	}.Build()
	File_pkg_pb_project_v1_project_proto = out.File
	file_pkg_pb_project_v1_project_proto_goTypes = nil
	file_pkg_pb_project_v1_project_proto_depIdxs = nil
}
