// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/pb/issues/v1/issues.proto

package issuesv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_NEW                Status = 1
	Status_ASSIGNED           Status = 2
	Status_IN_PROGRESS        Status = 3
	Status_RESOLVED           Status = 4
	Status_CLOSED             Status = 5
	Status_REOPENED           Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "NEW",
		2: "ASSIGNED",
		3: "IN_PROGRESS",
		4: "RESOLVED",
		5: "CLOSED",
		6: "REOPENED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"NEW":                1,
		"ASSIGNED":           2,
		"IN_PROGRESS":        3,
		"RESOLVED":           4,
		"CLOSED":             5,
		"REOPENED":           6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_issues_v1_issues_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_pb_issues_v1_issues_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{0}
}

type Resolution int32

const (
	Resolution_RESOLUTION_UNSPECIFIED Resolution = 0
	Resolution_FIXED                  Resolution = 1
	Resolution_INVALID                Resolution = 2
	Resolution_WONTFIX                Resolution = 3
	Resolution_WORKSFORME             Resolution = 4
)

// Enum value maps for Resolution.
var (
	Resolution_name = map[int32]string{
		0: "RESOLUTION_UNSPECIFIED",
		1: "FIXED",
		2: "INVALID",
		3: "WONTFIX",
		4: "WORKSFORME",
	}
	Resolution_value = map[string]int32{
		"RESOLUTION_UNSPECIFIED": 0,
		"FIXED":                  1,
		"INVALID":                2,
		"WONTFIX":                3,
		"WORKSFORME":             4,
	}
)

func (x Resolution) Enum() *Resolution {
	p := new(Resolution)
	*p = x
	return p
}

func (x Resolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resolution) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_issues_v1_issues_proto_enumTypes[1].Descriptor()
}

func (Resolution) Type() protoreflect.EnumType {
	return &file_pkg_pb_issues_v1_issues_proto_enumTypes[1]
}

func (x Resolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resolution.Descriptor instead.
func (Resolution) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{1}
}

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_COSMETIC         Type = 1
	Type_BUG              Type = 2
	Type_FEATURE          Type = 3
	Type_PERFORMANCE      Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "COSMETIC",
		2: "BUG",
		3: "FEATURE",
		4: "PERFORMANCE",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"COSMETIC":         1,
		"BUG":              2,
		"FEATURE":          3,
		"PERFORMANCE":      4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_issues_v1_issues_proto_enumTypes[2].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_pkg_pb_issues_v1_issues_proto_enumTypes[2]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{2}
}

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_CRITICAL             Priority = 1
	Priority_MAJOR                Priority = 2
	Priority_IMPORTANT            Priority = 3
	Priority_MINOR                Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "CRITICAL",
		2: "MAJOR",
		3: "IMPORTANT",
		4: "MINOR",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"CRITICAL":             1,
		"MAJOR":                2,
		"IMPORTANT":            3,
		"MINOR":                4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_issues_v1_issues_proto_enumTypes[3].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_pkg_pb_issues_v1_issues_proto_enumTypes[3]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{3}
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=issues.v1.Status" json:"status,omitempty"`
	Resolution    Resolution             `protobuf:"varint,5,opt,name=resolution,proto3,enum=issues.v1.Resolution" json:"resolution,omitempty"`
	Type          Type                   `protobuf:"varint,6,opt,name=type,proto3,enum=issues.v1.Type" json:"type,omitempty"`
	Priority      Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=issues.v1.Priority" json:"priority,omitempty"`
	ProjectId     string                 `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,9,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	CreateDate    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"` // uneditable
	ModifyDate    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=modify_date,json=modifyDate,proto3" json:"modify_date,omitempty"` // uneditable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *Issue) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Issue) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Issue) GetResolution() Resolution {
	if x != nil {
		return x.Resolution
	}
	return Resolution_RESOLUTION_UNSPECIFIED
}

func (x *Issue) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Issue) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Issue) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Issue) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *Issue) GetCreateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateDate
	}
	return nil
}

func (x *Issue) GetModifyDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifyDate
	}
	return nil
}

type CreateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Type          Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=issues.v1.Type" json:"type,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=issues.v1.Priority" json:"priority,omitempty"`
	ProjectId     string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIssueRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *CreateIssueRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateIssueRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateIssueRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Issue         *Issue                 `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type GetIssueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IssueId        string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	IncludeDetails bool                   `protobuf:"varint,2,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{3}
}

func (x *GetIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *GetIssueRequest) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	ProjectInfo   *ProjectInfo           `protobuf:"bytes,2,opt,name=project_info,json=projectInfo,proto3" json:"project_info,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{4}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

func (x *GetIssueResponse) GetProjectInfo() *ProjectInfo {
	if x != nil {
		return x.ProjectInfo
	}
	return nil
}

func (x *GetIssueResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UpdateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=issues.v1.Status" json:"status,omitempty"`
	Resolution    Resolution             `protobuf:"varint,5,opt,name=resolution,proto3,enum=issues.v1.Resolution" json:"resolution,omitempty"`
	Type          Type                   `protobuf:"varint,6,opt,name=type,proto3,enum=issues.v1.Type" json:"type,omitempty"`
	Priority      Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=issues.v1.Priority" json:"priority,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,8,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateIssueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateIssueRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *UpdateIssueRequest) GetResolution() Resolution {
	if x != nil {
		return x.Resolution
	}
	return Resolution_RESOLUTION_UNSPECIFIED
}

func (x *UpdateIssueRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *UpdateIssueRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateIssueRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Issue         *Issue                 `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type DeleteIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueRequest) Reset() {
	*x = DeleteIssueRequest{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueRequest) ProtoMessage() {}

func (x *DeleteIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueRequest.ProtoReflect.Descriptor instead.
func (*DeleteIssueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type DeleteIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Issue         *Issue                 `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueResponse) Reset() {
	*x = DeleteIssueResponse{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueResponse) ProtoMessage() {}

func (x *DeleteIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueResponse.ProtoReflect.Descriptor instead.
func (*DeleteIssueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type ListIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesRequest) Reset() {
	*x = ListIssuesRequest{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesRequest) ProtoMessage() {}

func (x *ListIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesRequest.ProtoReflect.Descriptor instead.
func (*ListIssuesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{9}
}

func (x *ListIssuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIssuesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesResponse) Reset() {
	*x = ListIssuesResponse{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesResponse) ProtoMessage() {}

func (x *ListIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesResponse.ProtoReflect.Descriptor instead.
func (*ListIssuesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{10}
}

func (x *ListIssuesResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListIssuesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ProjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_issues_v1_issues_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_issues_v1_issues_proto_rawDescGZIP(), []int{12}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_pkg_pb_issues_v1_issues_proto protoreflect.FileDescriptor

const file_pkg_pb_issues_v1_issues_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/pb/issues/v1/issues.proto\x12\tissues.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dproto/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xad\x04\n" +
	"\x05Issue\x12#\n" +
	"\bissue_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aissueId\x12#\n" +
	"\asummary\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\asummary\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03R\vdescription\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.issues.v1.StatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12?\n" +
	"\n" +
	"resolution\x18\x05 \x01(\x0e2\x15.issues.v1.ResolutionB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"resolution\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x0f.issues.v1.TypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x129\n" +
	"\bpriority\x18\a \x01(\x0e2\x13.issues.v1.PriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12'\n" +
	"\n" +
	"project_id\x18\b \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tprojectId\x12)\n" +
	"\vassignee_id\x18\t \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"assigneeId\x12;\n" +
	"\vcreate_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createDate\x12;\n" +
	"\vmodify_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifyDate\"\xce\x02\n" +
	"\x12CreateIssueRequest\x12#\n" +
	"\asummary\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\asummary\x120\n" +
	"\vdescription\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dH\x00R\vdescription\x88\x01\x01\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.issues.v1.TypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x129\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x13.issues.v1.PriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12'\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tprojectId\x12.\n" +
	"\vassignee_id\x18\x06 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01H\x01R\n" +
	"assigneeId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_assignee_id\"W\n" +
	"\x13CreateIssueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x05issue\x18\x02 \x01(\v2\x10.issues.v1.IssueR\x05issue\"_\n" +
	"\x0fGetIssueRequest\x12#\n" +
	"\bissue_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aissueId\x12'\n" +
	"\x0finclude_details\x18\x02 \x01(\bR\x0eincludeDetails\"\xa7\x01\n" +
	"\x10GetIssueResponse\x12&\n" +
	"\x05issue\x18\x01 \x01(\v2\x10.issues.v1.IssueR\x05issue\x129\n" +
	"\fproject_info\x18\x02 \x01(\v2\x16.issues.v1.ProjectInfoR\vprojectInfo\x120\n" +
	"\tuser_info\x18\x03 \x01(\v2\x13.issues.v1.UserInfoR\buserInfo\"\xc1\x03\n" +
	"\x12UpdateIssueRequest\x12#\n" +
	"\bissue_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aissueId\x12#\n" +
	"\asummary\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\asummary\x121\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03H\x00R\vdescription\x88\x01\x01\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.issues.v1.StatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12?\n" +
	"\n" +
	"resolution\x18\x05 \x01(\x0e2\x15.issues.v1.ResolutionB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"resolution\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x0f.issues.v1.TypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x129\n" +
	"\bpriority\x18\a \x01(\x0e2\x13.issues.v1.PriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12.\n" +
	"\vassignee_id\x18\b \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01H\x01R\n" +
	"assigneeId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_assignee_id\"W\n" +
	"\x13UpdateIssueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x05issue\x18\x02 \x01(\v2\x10.issues.v1.IssueR\x05issue\"9\n" +
	"\x12DeleteIssueRequest\x12#\n" +
	"\bissue_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aissueId\"W\n" +
	"\x13DeleteIssueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x05issue\x18\x02 \x01(\v2\x10.issues.v1.IssueR\x05issue\"[\n" +
	"\x11ListIssuesRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xe8\a(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"f\n" +
	"\x12ListIssuesResponse\x12(\n" +
	"\x06issues\x18\x01 \x03(\v2\x10.issues.v1.IssueR\x06issues\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"b\n" +
	"\vProjectInfo\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"u\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email*p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\f\n" +
	"\bASSIGNED\x10\x02\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x03\x12\f\n" +
	"\bRESOLVED\x10\x04\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x05\x12\f\n" +
	"\bREOPENED\x10\x06*]\n" +
	"\n" +
	"Resolution\x12\x1a\n" +
	"\x16RESOLUTION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05FIXED\x10\x01\x12\v\n" +
	"\aINVALID\x10\x02\x12\v\n" +
	"\aWONTFIX\x10\x03\x12\x0e\n" +
	"\n" +
	"WORKSFORME\x10\x04*Q\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCOSMETIC\x10\x01\x12\a\n" +
	"\x03BUG\x10\x02\x12\v\n" +
	"\aFEATURE\x10\x03\x12\x0f\n" +
	"\vPERFORMANCE\x10\x04*W\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCRITICAL\x10\x01\x12\t\n" +
	"\x05MAJOR\x10\x02\x12\r\n" +
	"\tIMPORTANT\x10\x03\x12\t\n" +
	"\x05MINOR\x10\x042\xa8\x04\n" +
	"\rIssuesService\x12g\n" +
	"\vCreateIssue\x12\x1d.issues.v1.CreateIssueRequest\x1a\x1e.issues.v1.CreateIssueResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/issues\x12f\n" +
	"\bGetIssue\x12\x1a.issues.v1.GetIssueRequest\x1a\x1b.issues.v1.GetIssueResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/issues/{issue_id}\x12r\n" +
	"\vUpdateIssue\x12\x1d.issues.v1.UpdateIssueRequest\x1a\x1e.issues.v1.UpdateIssueResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/v1/issues/{issue_id}\x12o\n" +
	"\vDeleteIssue\x12\x1d.issues.v1.DeleteIssueRequest\x1a\x1e.issues.v1.DeleteIssueResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/issues/{issue_id}\x12a\n" +
	"\n" +
	"ListIssues\x12\x1c.issues.v1.ListIssuesRequest\x1a\x1d.issues.v1.ListIssuesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/issuesB\x1bZ\x19pkg/pb/issues/v1;issuesv1b\x06proto3"

var (
	file_pkg_pb_issues_v1_issues_proto_rawDescOnce sync.Once
	file_pkg_pb_issues_v1_issues_proto_rawDescData []byte
)

func file_pkg_pb_issues_v1_issues_proto_rawDescGZIP() []byte {
	file_pkg_pb_issues_v1_issues_proto_rawDescOnce.Do(func() {
		file_pkg_pb_issues_v1_issues_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_issues_v1_issues_proto_rawDesc), len(file_pkg_pb_issues_v1_issues_proto_rawDesc)))
	})
	return file_pkg_pb_issues_v1_issues_proto_rawDescData
}

var file_pkg_pb_issues_v1_issues_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_pb_issues_v1_issues_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_pb_issues_v1_issues_proto_goTypes = []any{
	(Status)(0),                   // 0: issues.v1.Status
	(Resolution)(0),               // 1: issues.v1.Resolution
	(Type)(0),                     // 2: issues.v1.Type
	(Priority)(0),                 // 3: issues.v1.Priority
	(*Issue)(nil),                 // 4: issues.v1.Issue
	(*CreateIssueRequest)(nil),    // 5: issues.v1.CreateIssueRequest
	(*CreateIssueResponse)(nil),   // 6: issues.v1.CreateIssueResponse
	(*GetIssueRequest)(nil),       // 7: issues.v1.GetIssueRequest
	(*GetIssueResponse)(nil),      // 8: issues.v1.GetIssueResponse
	(*UpdateIssueRequest)(nil),    // 9: issues.v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),   // 10: issues.v1.UpdateIssueResponse
	(*DeleteIssueRequest)(nil),    // 11: issues.v1.DeleteIssueRequest
	(*DeleteIssueResponse)(nil),   // 12: issues.v1.DeleteIssueResponse
	(*ListIssuesRequest)(nil),     // 13: issues.v1.ListIssuesRequest
	(*ListIssuesResponse)(nil),    // 14: issues.v1.ListIssuesResponse
	(*ProjectInfo)(nil),           // 15: issues.v1.ProjectInfo
	(*UserInfo)(nil),              // 16: issues.v1.UserInfo
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_pkg_pb_issues_v1_issues_proto_depIdxs = []int32{
	0,  // 0: issues.v1.Issue.status:type_name -> issues.v1.Status
	1,  // 1: issues.v1.Issue.resolution:type_name -> issues.v1.Resolution
	2,  // 2: issues.v1.Issue.type:type_name -> issues.v1.Type
	3,  // 3: issues.v1.Issue.priority:type_name -> issues.v1.Priority
	17, // 4: issues.v1.Issue.create_date:type_name -> google.protobuf.Timestamp
	17, // 5: issues.v1.Issue.modify_date:type_name -> google.protobuf.Timestamp
	2,  // 6: issues.v1.CreateIssueRequest.type:type_name -> issues.v1.Type
	3,  // 7: issues.v1.CreateIssueRequest.priority:type_name -> issues.v1.Priority
	4,  // 8: issues.v1.CreateIssueResponse.issue:type_name -> issues.v1.Issue
	4,  // 9: issues.v1.GetIssueResponse.issue:type_name -> issues.v1.Issue
	15, // 10: issues.v1.GetIssueResponse.project_info:type_name -> issues.v1.ProjectInfo
	16, // 11: issues.v1.GetIssueResponse.user_info:type_name -> issues.v1.UserInfo
	0,  // 12: issues.v1.UpdateIssueRequest.status:type_name -> issues.v1.Status
	1,  // 13: issues.v1.UpdateIssueRequest.resolution:type_name -> issues.v1.Resolution
	2,  // 14: issues.v1.UpdateIssueRequest.type:type_name -> issues.v1.Type
	3,  // 15: issues.v1.UpdateIssueRequest.priority:type_name -> issues.v1.Priority
	4,  // 16: issues.v1.UpdateIssueResponse.issue:type_name -> issues.v1.Issue
	4,  // 17: issues.v1.DeleteIssueResponse.issue:type_name -> issues.v1.Issue
	4,  // 18: issues.v1.ListIssuesResponse.issues:type_name -> issues.v1.Issue
	5,  // 19: issues.v1.IssuesService.CreateIssue:input_type -> issues.v1.CreateIssueRequest
	7,  // 20: issues.v1.IssuesService.GetIssue:input_type -> issues.v1.GetIssueRequest
	9,  // 21: issues.v1.IssuesService.UpdateIssue:input_type -> issues.v1.UpdateIssueRequest
	11, // 22: issues.v1.IssuesService.DeleteIssue:input_type -> issues.v1.DeleteIssueRequest
	13, // 23: issues.v1.IssuesService.ListIssues:input_type -> issues.v1.ListIssuesRequest
	6,  // 24: issues.v1.IssuesService.CreateIssue:output_type -> issues.v1.CreateIssueResponse
	8,  // 25: issues.v1.IssuesService.GetIssue:output_type -> issues.v1.GetIssueResponse
	10, // 26: issues.v1.IssuesService.UpdateIssue:output_type -> issues.v1.UpdateIssueResponse
	12, // 27: issues.v1.IssuesService.DeleteIssue:output_type -> issues.v1.DeleteIssueResponse
	14, // 28: issues.v1.IssuesService.ListIssues:output_type -> issues.v1.ListIssuesResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_pb_issues_v1_issues_proto_init() }
func file_pkg_pb_issues_v1_issues_proto_init() {
	if File_pkg_pb_issues_v1_issues_proto != nil {
		return
	}
	file_pkg_pb_issues_v1_issues_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_pb_issues_v1_issues_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_issues_v1_issues_proto_rawDesc), len(file_pkg_pb_issues_v1_issues_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_issues_v1_issues_proto_goTypes,
		DependencyIndexes: file_pkg_pb_issues_v1_issues_proto_depIdxs,
		EnumInfos:         file_pkg_pb_issues_v1_issues_proto_enumTypes,
		MessageInfos:      file_pkg_pb_issues_v1_issues_proto_msgTypes,
	}.Build()
	File_pkg_pb_issues_v1_issues_proto = out.File
	file_pkg_pb_issues_v1_issues_proto_goTypes = nil
	file_pkg_pb_issues_v1_issues_proto_depIdxs = nil
}
