// Code generated by MockGen. DO NOT EDIT.
// Source: c:/Users/mohammed_yasin/Downloads/issue-tracker-mohammed_yasin-in-mem/pkg/svc/project_service.go
//
// Generated by this command:
//
//	mockgen -source=c:/Users/mohammed_yasin/Downloads/issue-tracker-mohammed_yasin-in-mem/pkg/svc/project_service.go -destination=c:/Users/mohammed_yasin/Downloads/issue-tracker-mohammed_yasin-in-mem/mocks/mocks_project_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
